# Generated by Django 4.2 on 2023-05-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('id_alumno', models.IntegerField(verbose_name='idalumno')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('id_club', models.IntegerField(verbose_name='idclub')),
                ('nombre', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('id_profesor', models.IntegerField(verbose_name='idprofesor')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('id_reserva', models.IntegerField(verbose_name='idreserva')),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
                ('id_profesor', models.CharField(max_length=50, verbose_name='idprofesor')),
                ('id_club', models.CharField(max_length=50, verbose_name='idclub')),
                ('id_alumno', models.CharField(max_length=50, verbose_name='idalumno')),
                ('num_cancha', models.IntegerField()),
            ],
        ),
    ]
